// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type AgentResponsePayload byte

const (
	AgentResponsePayloadNONE                         AgentResponsePayload = 0
	AgentResponsePayloadHealthCheckResponse          AgentResponsePayload = 1
	AgentResponsePayloadMachineInfoResponse          AgentResponsePayload = 2
	AgentResponsePayloadIpmiInfoResponse             AgentResponsePayload = 3
	AgentResponsePayloadIpmiSetupResponse            AgentResponsePayload = 4
	AgentResponsePayloadCommandExecutionResponse     AgentResponsePayload = 5
	AgentResponsePayloadCommandExecutionOnceResponse AgentResponsePayload = 6
	AgentResponsePayloadFilePushStartResponse        AgentResponsePayload = 7
	AgentResponsePayloadFilePushSegmentResponse      AgentResponsePayload = 8
)

var EnumNamesAgentResponsePayload = map[AgentResponsePayload]string{
	AgentResponsePayloadNONE:                         "NONE",
	AgentResponsePayloadHealthCheckResponse:          "HealthCheckResponse",
	AgentResponsePayloadMachineInfoResponse:          "MachineInfoResponse",
	AgentResponsePayloadIpmiInfoResponse:             "IpmiInfoResponse",
	AgentResponsePayloadIpmiSetupResponse:            "IpmiSetupResponse",
	AgentResponsePayloadCommandExecutionResponse:     "CommandExecutionResponse",
	AgentResponsePayloadCommandExecutionOnceResponse: "CommandExecutionOnceResponse",
	AgentResponsePayloadFilePushStartResponse:        "FilePushStartResponse",
	AgentResponsePayloadFilePushSegmentResponse:      "FilePushSegmentResponse",
}

var EnumValuesAgentResponsePayload = map[string]AgentResponsePayload{
	"NONE":                         AgentResponsePayloadNONE,
	"HealthCheckResponse":          AgentResponsePayloadHealthCheckResponse,
	"MachineInfoResponse":          AgentResponsePayloadMachineInfoResponse,
	"IpmiInfoResponse":             AgentResponsePayloadIpmiInfoResponse,
	"IpmiSetupResponse":            AgentResponsePayloadIpmiSetupResponse,
	"CommandExecutionResponse":     AgentResponsePayloadCommandExecutionResponse,
	"CommandExecutionOnceResponse": AgentResponsePayloadCommandExecutionOnceResponse,
	"FilePushStartResponse":        AgentResponsePayloadFilePushStartResponse,
	"FilePushSegmentResponse":      AgentResponsePayloadFilePushSegmentResponse,
}

func (v AgentResponsePayload) String() string {
	if s, ok := EnumNamesAgentResponsePayload[v]; ok {
		return s
	}
	return "AgentResponsePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
