// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AgentResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAgentResponse(buf []byte, offset flatbuffers.UOffsetT) *AgentResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AgentResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishAgentResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAgentResponse(buf []byte, offset flatbuffers.UOffsetT) *AgentResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AgentResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAgentResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AgentResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AgentResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AgentResponse) Version() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *AgentResponse) MutateVersion(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *AgentResponse) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AgentResponse) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *AgentResponse) PayloadType() AgentResponsePayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return AgentResponsePayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *AgentResponse) MutatePayloadType(n AgentResponsePayload) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *AgentResponse) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *AgentResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AgentResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func AgentResponseAddVersion(builder *flatbuffers.Builder, version byte) {
	builder.PrependByteSlot(0, version, 1)
}
func AgentResponseAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(1, id, 0)
}
func AgentResponseAddPayloadType(builder *flatbuffers.Builder, payloadType AgentResponsePayload) {
	builder.PrependByteSlot(2, byte(payloadType), 0)
}
func AgentResponseAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(payload), 0)
}
func AgentResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(error), 0)
}
func AgentResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
