// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CommandExecutionOnceResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsCommandExecutionOnceResponse(buf []byte, offset flatbuffers.UOffsetT) *CommandExecutionOnceResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommandExecutionOnceResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommandExecutionOnceResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCommandExecutionOnceResponse(buf []byte, offset flatbuffers.UOffsetT) *CommandExecutionOnceResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CommandExecutionOnceResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommandExecutionOnceResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CommandExecutionOnceResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommandExecutionOnceResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommandExecutionOnceResponse) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CommandExecutionOnceResponse) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func CommandExecutionOnceResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CommandExecutionOnceResponseAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(0, success, false)
}
func CommandExecutionOnceResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
