// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CommandExecutionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCommandExecutionRequest(buf []byte, offset flatbuffers.UOffsetT) *CommandExecutionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommandExecutionRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommandExecutionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCommandExecutionRequest(buf []byte, offset flatbuffers.UOffsetT) *CommandExecutionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CommandExecutionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommandExecutionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CommandExecutionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommandExecutionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommandExecutionRequest) Type() CommandExecutionType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return CommandExecutionType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CommandExecutionRequest) MutateType(n CommandExecutionType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *CommandExecutionRequest) Workdir() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CommandExecutionRequest) Command() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CommandExecutionRequest) Args(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *CommandExecutionRequest) ArgsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CommandExecutionRequest) Timeout() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CommandExecutionRequest) MutateTimeout(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func CommandExecutionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func CommandExecutionRequestAddType(builder *flatbuffers.Builder, type_ CommandExecutionType) {
	builder.PrependByteSlot(0, byte(type_), 0)
}
func CommandExecutionRequestAddWorkdir(builder *flatbuffers.Builder, workdir flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(workdir), 0)
}
func CommandExecutionRequestAddCommand(builder *flatbuffers.Builder, command flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(command), 0)
}
func CommandExecutionRequestAddArgs(builder *flatbuffers.Builder, args flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(args), 0)
}
func CommandExecutionRequestStartArgsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CommandExecutionRequestAddTimeout(builder *flatbuffers.Builder, timeout uint64) {
	builder.PrependUint64Slot(4, timeout, 0)
}
func CommandExecutionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
