// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CommandExecutionResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsCommandExecutionResponse(buf []byte, offset flatbuffers.UOffsetT) *CommandExecutionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommandExecutionResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommandExecutionResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCommandExecutionResponse(buf []byte, offset flatbuffers.UOffsetT) *CommandExecutionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CommandExecutionResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommandExecutionResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CommandExecutionResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommandExecutionResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommandExecutionResponse) Code() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CommandExecutionResponse) MutateCode(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *CommandExecutionResponse) Finished() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CommandExecutionResponse) MutateFinished(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *CommandExecutionResponse) Stdout() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CommandExecutionResponse) Stderr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CommandExecutionResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func CommandExecutionResponseAddCode(builder *flatbuffers.Builder, code byte) {
	builder.PrependByteSlot(0, code, 0)
}
func CommandExecutionResponseAddFinished(builder *flatbuffers.Builder, finished bool) {
	builder.PrependBoolSlot(1, finished, false)
}
func CommandExecutionResponseAddStdout(builder *flatbuffers.Builder, stdout flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(stdout), 0)
}
func CommandExecutionResponseAddStderr(builder *flatbuffers.Builder, stderr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(stderr), 0)
}
func CommandExecutionResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
