// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type CommandExecutionType byte

const (
	CommandExecutionTypeWait   CommandExecutionType = 0
	CommandExecutionTypeStream CommandExecutionType = 1
	CommandExecutionTypeOnce   CommandExecutionType = 2
)

var EnumNamesCommandExecutionType = map[CommandExecutionType]string{
	CommandExecutionTypeWait:   "Wait",
	CommandExecutionTypeStream: "Stream",
	CommandExecutionTypeOnce:   "Once",
}

var EnumValuesCommandExecutionType = map[string]CommandExecutionType{
	"Wait":   CommandExecutionTypeWait,
	"Stream": CommandExecutionTypeStream,
	"Once":   CommandExecutionTypeOnce,
}

func (v CommandExecutionType) String() string {
	if s, ok := EnumNamesCommandExecutionType[v]; ok {
		return s
	}
	return "CommandExecutionType(" + strconv.FormatInt(int64(v), 10) + ")"
}
