// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ControllerRequestPayload byte

const (
	ControllerRequestPayloadNONE                    ControllerRequestPayload = 0
	ControllerRequestPayloadHealthCheckRequest      ControllerRequestPayload = 1
	ControllerRequestPayloadMachineInfoRequest      ControllerRequestPayload = 2
	ControllerRequestPayloadIpmiInfoRequest         ControllerRequestPayload = 3
	ControllerRequestPayloadIpmiSetupRequest        ControllerRequestPayload = 4
	ControllerRequestPayloadCommandExecutionRequest ControllerRequestPayload = 5
	ControllerRequestPayloadFilePushStartRequest    ControllerRequestPayload = 6
	ControllerRequestPayloadFilePushSegmentRequest  ControllerRequestPayload = 7
)

var EnumNamesControllerRequestPayload = map[ControllerRequestPayload]string{
	ControllerRequestPayloadNONE:                    "NONE",
	ControllerRequestPayloadHealthCheckRequest:      "HealthCheckRequest",
	ControllerRequestPayloadMachineInfoRequest:      "MachineInfoRequest",
	ControllerRequestPayloadIpmiInfoRequest:         "IpmiInfoRequest",
	ControllerRequestPayloadIpmiSetupRequest:        "IpmiSetupRequest",
	ControllerRequestPayloadCommandExecutionRequest: "CommandExecutionRequest",
	ControllerRequestPayloadFilePushStartRequest:    "FilePushStartRequest",
	ControllerRequestPayloadFilePushSegmentRequest:  "FilePushSegmentRequest",
}

var EnumValuesControllerRequestPayload = map[string]ControllerRequestPayload{
	"NONE":                    ControllerRequestPayloadNONE,
	"HealthCheckRequest":      ControllerRequestPayloadHealthCheckRequest,
	"MachineInfoRequest":      ControllerRequestPayloadMachineInfoRequest,
	"IpmiInfoRequest":         ControllerRequestPayloadIpmiInfoRequest,
	"IpmiSetupRequest":        ControllerRequestPayloadIpmiSetupRequest,
	"CommandExecutionRequest": ControllerRequestPayloadCommandExecutionRequest,
	"FilePushStartRequest":    ControllerRequestPayloadFilePushStartRequest,
	"FilePushSegmentRequest":  ControllerRequestPayloadFilePushSegmentRequest,
}

func (v ControllerRequestPayload) String() string {
	if s, ok := EnumNamesControllerRequestPayload[v]; ok {
		return s
	}
	return "ControllerRequestPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
