// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CpuInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsCpuInfo(buf []byte, offset flatbuffers.UOffsetT) *CpuInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CpuInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishCpuInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCpuInfo(buf []byte, offset flatbuffers.UOffsetT) *CpuInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CpuInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCpuInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CpuInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CpuInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CpuInfo) Architecture() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CpuInfo) Vendor() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CpuInfo) Model() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CpuInfo) Cpus() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CpuInfo) MutateCpus(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *CpuInfo) Threads() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CpuInfo) MutateThreads(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *CpuInfo) Sockets() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CpuInfo) MutateSockets(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *CpuInfo) NumaNodes() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CpuInfo) MutateNumaNodes(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func CpuInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func CpuInfoAddArchitecture(builder *flatbuffers.Builder, architecture flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(architecture), 0)
}
func CpuInfoAddVendor(builder *flatbuffers.Builder, vendor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(vendor), 0)
}
func CpuInfoAddModel(builder *flatbuffers.Builder, model flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(model), 0)
}
func CpuInfoAddCpus(builder *flatbuffers.Builder, cpus uint32) {
	builder.PrependUint32Slot(3, cpus, 0)
}
func CpuInfoAddThreads(builder *flatbuffers.Builder, threads uint32) {
	builder.PrependUint32Slot(4, threads, 0)
}
func CpuInfoAddSockets(builder *flatbuffers.Builder, sockets uint32) {
	builder.PrependUint32Slot(5, sockets, 0)
}
func CpuInfoAddNumaNodes(builder *flatbuffers.Builder, numaNodes uint32) {
	builder.PrependUint32Slot(6, numaNodes, 0)
}
func CpuInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
