// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FilePushStartResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsFilePushStartResponse(buf []byte, offset flatbuffers.UOffsetT) *FilePushStartResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FilePushStartResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishFilePushStartResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFilePushStartResponse(buf []byte, offset flatbuffers.UOffsetT) *FilePushStartResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FilePushStartResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFilePushStartResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FilePushStartResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FilePushStartResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FilePushStartResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FilePushStartResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func FilePushStartResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FilePushStartResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func FilePushStartResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
