// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FilePullSegmentRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsFilePullSegmentRequest(buf []byte, offset flatbuffers.UOffsetT) *FilePullSegmentRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FilePullSegmentRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishFilePullSegmentRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFilePullSegmentRequest(buf []byte, offset flatbuffers.UOffsetT) *FilePullSegmentRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FilePullSegmentRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFilePullSegmentRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FilePullSegmentRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FilePullSegmentRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FilePullSegmentRequest) StartId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FilePullSegmentRequest) MutateStartId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *FilePullSegmentRequest) End() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FilePullSegmentRequest) MutateEnd(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *FilePullSegmentRequest) SegmentId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FilePullSegmentRequest) MutateSegmentId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func FilePullSegmentRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FilePullSegmentRequestAddStartId(builder *flatbuffers.Builder, startId uint64) {
	builder.PrependUint64Slot(0, startId, 0)
}
func FilePullSegmentRequestAddEnd(builder *flatbuffers.Builder, end bool) {
	builder.PrependBoolSlot(1, end, false)
}
func FilePullSegmentRequestAddSegmentId(builder *flatbuffers.Builder, segmentId uint64) {
	builder.PrependUint64Slot(2, segmentId, 0)
}
func FilePullSegmentRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
