// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FilePushStartRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsFilePushStartRequest(buf []byte, offset flatbuffers.UOffsetT) *FilePushStartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FilePushStartRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishFilePushStartRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFilePushStartRequest(buf []byte, offset flatbuffers.UOffsetT) *FilePushStartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FilePushStartRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFilePushStartRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FilePushStartRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FilePushStartRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FilePushStartRequest) Dest() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FilePushStartRequest) Size() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FilePushStartRequest) MutateSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *FilePushStartRequest) SegmentSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FilePushStartRequest) MutateSegmentSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *FilePushStartRequest) Compression() Compression {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return Compression(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FilePushStartRequest) MutateCompression(n Compression) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *FilePushStartRequest) Xxh3() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FilePushStartRequest) MutateXxh3(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func FilePushStartRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func FilePushStartRequestAddDest(builder *flatbuffers.Builder, dest flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dest), 0)
}
func FilePushStartRequestAddSize(builder *flatbuffers.Builder, size uint64) {
	builder.PrependUint64Slot(1, size, 0)
}
func FilePushStartRequestAddSegmentSize(builder *flatbuffers.Builder, segmentSize uint64) {
	builder.PrependUint64Slot(2, segmentSize, 0)
}
func FilePushStartRequestAddCompression(builder *flatbuffers.Builder, compression Compression) {
	builder.PrependByteSlot(3, byte(compression), 0)
}
func FilePushStartRequestAddXxh3(builder *flatbuffers.Builder, xxh3 uint64) {
	builder.PrependUint64Slot(4, xxh3, 0)
}
func FilePushStartRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
