// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FilePullStartRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsFilePullStartRequest(buf []byte, offset flatbuffers.UOffsetT) *FilePullStartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FilePullStartRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishFilePullStartRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFilePullStartRequest(buf []byte, offset flatbuffers.UOffsetT) *FilePullStartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FilePullStartRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFilePullStartRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FilePullStartRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FilePullStartRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FilePullStartRequest) Src() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FilePullStartRequest) SegmentSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FilePullStartRequest) MutateSegmentSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *FilePullStartRequest) Compression() Compression {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Compression(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FilePullStartRequest) MutateCompression(n Compression) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func FilePullStartRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FilePullStartRequestAddSrc(builder *flatbuffers.Builder, src flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(src), 0)
}
func FilePullStartRequestAddSegmentSize(builder *flatbuffers.Builder, segmentSize uint64) {
	builder.PrependUint64Slot(1, segmentSize, 0)
}
func FilePullStartRequestAddCompression(builder *flatbuffers.Builder, compression Compression) {
	builder.PrependByteSlot(2, byte(compression), 0)
}
func FilePullStartRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
