// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FilePullStartResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsFilePullStartResponse(buf []byte, offset flatbuffers.UOffsetT) *FilePullStartResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FilePullStartResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishFilePullStartResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFilePullStartResponse(buf []byte, offset flatbuffers.UOffsetT) *FilePullStartResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FilePullStartResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFilePullStartResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FilePullStartResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FilePullStartResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FilePullStartResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FilePullStartResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *FilePullStartResponse) Size() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FilePullStartResponse) MutateSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *FilePullStartResponse) Xxh3() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FilePullStartResponse) MutateXxh3(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func FilePullStartResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FilePullStartResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func FilePullStartResponseAddSize(builder *flatbuffers.Builder, size uint64) {
	builder.PrependUint64Slot(1, size, 0)
}
func FilePullStartResponseAddXxh3(builder *flatbuffers.Builder, xxh3 uint64) {
	builder.PrependUint64Slot(2, xxh3, 0)
}
func FilePullStartResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
