// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HealthCheckRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsHealthCheckRequest(buf []byte, offset flatbuffers.UOffsetT) *HealthCheckRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HealthCheckRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishHealthCheckRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHealthCheckRequest(buf []byte, offset flatbuffers.UOffsetT) *HealthCheckRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HealthCheckRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHealthCheckRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HealthCheckRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HealthCheckRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func HealthCheckRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func HealthCheckRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
