// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type HealthStatus byte

const (
	HealthStatusOk        HealthStatus = 0
	HealthStatusDowngrade HealthStatus = 1
	HealthStatusError     HealthStatus = 2
)

var EnumNamesHealthStatus = map[HealthStatus]string{
	HealthStatusOk:        "Ok",
	HealthStatusDowngrade: "Downgrade",
	HealthStatusError:     "Error",
}

var EnumValuesHealthStatus = map[string]HealthStatus{
	"Ok":        HealthStatusOk,
	"Downgrade": HealthStatusDowngrade,
	"Error":     HealthStatusError,
}

func (v HealthStatus) String() string {
	if s, ok := EnumNamesHealthStatus[v]; ok {
		return s
	}
	return "HealthStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
