// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HealthCheckResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsHealthCheckResponse(buf []byte, offset flatbuffers.UOffsetT) *HealthCheckResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HealthCheckResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishHealthCheckResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHealthCheckResponse(buf []byte, offset flatbuffers.UOffsetT) *HealthCheckResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HealthCheckResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHealthCheckResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HealthCheckResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HealthCheckResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HealthCheckResponse) Status() HealthStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return HealthStatus(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *HealthCheckResponse) MutateStatus(n HealthStatus) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *HealthCheckResponse) StartTime() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HealthCheckResponse) MutateStartTime(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *HealthCheckResponse) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func HealthCheckResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func HealthCheckResponseAddStatus(builder *flatbuffers.Builder, status HealthStatus) {
	builder.PrependByteSlot(0, byte(status), 0)
}
func HealthCheckResponseAddStartTime(builder *flatbuffers.Builder, startTime uint64) {
	builder.PrependUint64Slot(1, startTime, 0)
}
func HealthCheckResponseAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(reason), 0)
}
func HealthCheckResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
