// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IpmiSetupRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsIpmiSetupRequest(buf []byte, offset flatbuffers.UOffsetT) *IpmiSetupRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IpmiSetupRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishIpmiSetupRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIpmiSetupRequest(buf []byte, offset flatbuffers.UOffsetT) *IpmiSetupRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IpmiSetupRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIpmiSetupRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IpmiSetupRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IpmiSetupRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IpmiSetupRequest) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *IpmiSetupRequest) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func IpmiSetupRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func IpmiSetupRequestAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(username), 0)
}
func IpmiSetupRequestAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(password), 0)
}
func IpmiSetupRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
