// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IpmiSetupResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsIpmiSetupResponse(buf []byte, offset flatbuffers.UOffsetT) *IpmiSetupResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IpmiSetupResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishIpmiSetupResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIpmiSetupResponse(buf []byte, offset flatbuffers.UOffsetT) *IpmiSetupResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IpmiSetupResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIpmiSetupResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IpmiSetupResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IpmiSetupResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IpmiSetupResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *IpmiSetupResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func IpmiSetupResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func IpmiSetupResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func IpmiSetupResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
