// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Ipv4Info struct {
	_tab flatbuffers.Table
}

func GetRootAsIpv4Info(buf []byte, offset flatbuffers.UOffsetT) *Ipv4Info {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ipv4Info{}
	x.Init(buf, n+offset)
	return x
}

func FinishIpv4InfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIpv4Info(buf []byte, offset flatbuffers.UOffsetT) *Ipv4Info {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Ipv4Info{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIpv4InfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Ipv4Info) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ipv4Info) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Ipv4Info) DhcpEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Ipv4Info) MutateDhcpEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *Ipv4Info) Address() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ipv4Info) MutateAddress(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Ipv4Info) PrefixLength() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ipv4Info) MutatePrefixLength(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *Ipv4Info) Gateway() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ipv4Info) MutateGateway(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *Ipv4Info) Dns() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ipv4Info) MutateDns(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func Ipv4InfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func Ipv4InfoAddDhcpEnabled(builder *flatbuffers.Builder, dhcpEnabled bool) {
	builder.PrependBoolSlot(0, dhcpEnabled, false)
}
func Ipv4InfoAddAddress(builder *flatbuffers.Builder, address uint32) {
	builder.PrependUint32Slot(1, address, 0)
}
func Ipv4InfoAddPrefixLength(builder *flatbuffers.Builder, prefixLength byte) {
	builder.PrependByteSlot(2, prefixLength, 0)
}
func Ipv4InfoAddGateway(builder *flatbuffers.Builder, gateway uint32) {
	builder.PrependUint32Slot(3, gateway, 0)
}
func Ipv4InfoAddDns(builder *flatbuffers.Builder, dns uint32) {
	builder.PrependUint32Slot(4, dns, 0)
}
func Ipv4InfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
