// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MachineInfoRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsMachineInfoRequest(buf []byte, offset flatbuffers.UOffsetT) *MachineInfoRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MachineInfoRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishMachineInfoRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMachineInfoRequest(buf []byte, offset flatbuffers.UOffsetT) *MachineInfoRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MachineInfoRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMachineInfoRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MachineInfoRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MachineInfoRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func MachineInfoRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func MachineInfoRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
