// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MachineInfoResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsMachineInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *MachineInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MachineInfoResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishMachineInfoResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMachineInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *MachineInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MachineInfoResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMachineInfoResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MachineInfoResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MachineInfoResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MachineInfoResponse) ProductUuid(obj *UUID) *UUID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(UUID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MachineInfoResponse) Cpu(obj *CpuInfo) *CpuInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CpuInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MachineInfoResponse) Memory() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MachineInfoResponse) MutateMemory(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *MachineInfoResponse) BlockDevices(obj *BlkInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MachineInfoResponse) BlockDevicesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MachineInfoResponse) Nics(obj *NicInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MachineInfoResponse) NicsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MachineInfoResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MachineInfoResponseAddProductUuid(builder *flatbuffers.Builder, productUuid flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(productUuid), 0)
}
func MachineInfoResponseAddCpu(builder *flatbuffers.Builder, cpu flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cpu), 0)
}
func MachineInfoResponseAddMemory(builder *flatbuffers.Builder, memory uint64) {
	builder.PrependUint64Slot(2, memory, 0)
}
func MachineInfoResponseAddBlockDevices(builder *flatbuffers.Builder, blockDevices flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(blockDevices), 0)
}
func MachineInfoResponseStartBlockDevicesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MachineInfoResponseAddNics(builder *flatbuffers.Builder, nics flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(nics), 0)
}
func MachineInfoResponseStartNicsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MachineInfoResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
